openapi: 3.0.0
info:
  title: WasaPhoto
  version: 1.0.0
  description: |
    This is a simple API for a photo sharing service.
    You can upload photos, like photos, and comment on photos.
    You can also see who has liked or commented on a photo.
    This API is meant to be used with the WasaPhoto web application.
    You can find the source code for the web application 
    at https://github.com/matteo-mariotti/WASA_Photo_2022_2023

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  
  schemas:
    identifier:
      type: string
      pattern: "^[a-z0-9]*$"
      description: identifier
      example: "abcdef012345"
      maxLength: 12
      minLength: 12

    comment:
      type: string
      pattern: "^[a-zA-Z0-9 .,:]*$"
      description: comment
      example: "This is a comment"
      minLength: 1
      maxLength: 256

    photo:
      type: object
      properties:
        id:
          type: integer
          description: photo identifier     
        image:
            type: string
            format: binary
        likes:
            type: array
            items:
              $ref: "#/components/schemas/identifier"
        comments:
            type: array
            items:
              type: object
              properties:
                user:
                  $ref: "#/components/schemas/identifier"
                comment:
                  $ref: "#/components/schemas/comment"
              
    profile:
      type: object
      properties:
        username:
          type: string
          example: "Maria"
          pattern: "ˆ.*?$"
          minLength: 3
          maxLength: 16
        photos:
          description: List of photos uploaded by the user
          type: array
          items:
            $ref: "#/components/schemas/photo"
        followers:
          type: array
          items:
            $ref: "#/components/schemas/identifier"
        following:
          type: array
          items:
            $ref: "#/components/schemas/identifier"
        blocked:
          type: array
          items:
            $ref: "#/components/schemas/identifier"
  responses:
    NotFound:
      description: The specified resource was not found
    Unauthorized:
      description: Unauthorized

security:
  - BearerAuth: []

paths:
  /session:
    post:
      security: [] #No security is required to login into the application
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: "ˆ.*?$"
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        "201":
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    # change here if you decide to use an integer or any other type of identifier
                    type: string
                    example: "abcdef012345"
  /home:
    get:
      summary: Returns the photos of the users that the user is following (the stream)
      tags: ["home"]
      operationId: getMyStream
      responses:
        "200":
          description: Photos of the users that the user is following
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/photo"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
  /users:
    get:
      summary: Get the list all users
      tags: ["users"]
      description: |
        Get all users
      operationId: getUsers
      responses:
        "200":
          description: Users list retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/identifier"
                example:
                  ["abcdef012345","abcdef012346","abcdef012347"]
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
  /users/{userID}:
    
    parameters:
      - name: userID
        in: path
        description: User ID
        required: true
        schema:
          $ref: "#/components/schemas/identifier"
    get:
      tags: ["users"]
      summary: Get the user profile
      description: |
        Get the user's profile using the given identifier
      operationId: getUserProfile
      responses:
        "200":
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/profile"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
  /profile:
    get:
      tags: ["profile"]
      summary: Get the user profile
      description: |
        Get the user's profile using the given identifier
      operationId: getMyProfile
      responses:
        "200":
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/profile"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
    post:
      summary: Update the username
      tags: ["profile"]
      description: |
        Update the username profile (if available)
      operationId: setMyUserName
      requestBody:
        description: newUserName
        content:
          application/json:
            schema:
              type: string
              example: Maria
              pattern: "ˆ.*?$"
              minLength: 3
              maxLength: 16
        required: true
      responses:
        "200":
          description: User profile updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/profile"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          description: Username already taken
        "404":
          $ref: "#/components/responses/NotFound"
  /bans/{blockedID}:
    parameters:
      - name: blockedID
        in: path
        description: User to be blocked/unblocked
        required: true
        schema:
          $ref: "#/components/schemas/identifier"
    put:
      tags: ["ban"]
      summary: Block a user from the logged in user
      description: |
        Block a user 
      operationId: banUser
      responses:
        "200":
          description: User blocked successfully
        
    delete:
      tags: ["ban"]
      summary: Unblock a user from the logged in user
      description: |
        Unblock a user 
      operationId: unbanUser
      responses:
        "200":
          description: User unblocked successfully
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
  /followers/{followerID}:
    parameters:
      - name: followerID
        in: path
        description: User to be followed/unfollowed
        required: true
        schema:
          $ref: "#/components/schemas/identifier"
    put:
      tags: ["follow"]
      summary: Follow a user
      description: |
        Follow a user 
      operationId: followUser
      responses:
        "200":
          description: User followed successfully
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      summary: Unfollow a user
      tags: ["follow"]
      description: |
        Unfollow a user 
      operationId: unfollowUser
      responses:
        "200":
          description: User unfollowed successfully
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

  /like/{photoID}:
    parameters:
      - name: photoID
        in: path
        description: Photo to be liked/unliked
        required: true
        schema:
          $ref: "#/components/schemas/identifier"
    put:
      tags: ["photo"]
      summary: Like a photo
      description: |
        Like a photo 
      operationId: likePhoto
      responses:
        "200":
          description: Photo liked successfully
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      tags: ["photo"]
      summary: Unlike a photo
      description: |
        Unlike a photo 
      operationId: unlikePhoto
      responses:
        "200":
          description: Photo unliked successfully
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
    
  /comment/{photoID}:
    parameters:
      - name: photoID
        in: path
        description: Photo to be commented
        required: true
        schema:
          $ref: "#/components/schemas/identifier"
    post:
      tags: ["photo"]
      summary: Comment a photo
      description: |
        Comment a photo 
      operationId: commentPhoto
      requestBody:
        description: comment
        content:
          application/json:
            schema:
              type: string
              example: Nice photo!
              pattern: "ˆ.*?$"
              minLength: 3
              maxLength: 256
        required: true
      responses:
        "200":
          description: Photo commented successfully
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
  /photos:
    post:
      tags: ["photo"]
      summary: Upload a photo
      description: |
        Upload a photo 
      operationId: uploadPhoto
      requestBody:
        description: photo
        content:
          image/png:
            schema:
              type: string
              format: binary
        required: true
      responses:
        "200":
          description: Photo uploaded successfully
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
  /photos/{photoID}:
    parameters:
      - name: photoID
        in: path
        description: Photo to be deleted
        required: true
        schema:
          type: integer
          description: photo identifier     
    delete:
      tags: ["photo"]
      summary: Delete a photo
      description: |
        Delete the photo with the given identifier 
      operationId: deletePhoto
      responses:
        "200":
          description: Photo deleted successfully
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"